fujin:
  enabled: true
  addr: :4848
  ping_interval: 5s
  ping_timeout: 10s
  ping_stream: false
  ping_max_retries: 5
  write_deadline: 10s
  force_terminate_timeout: 15s
  tls:
    enabled: true
    server_cert_pem_path: /assets/certs/fujin.io.pem
    server_key_pem_path: /assets/certs/fujin.io-key.pem
  quic:
    max_incoming_streams: 1000
    max_idle_timeout: 5s
    keepalive_period: 2s
  observability_enabled: false
grpc:
  enabled: true
  addr: :4849
  observability_enabled: false
connectors:
  nsq_connector:
    protocol: nsq
    settings:
      common: {}
      clients:
        pub:
          address: "localhost:4150"
          topic: my_topic
          pool:
            size: 10000
            pre_alloc: true
            release_timeout: 5s
        sub:
          addresses: ["localhost:4150"]
          # lookupd_addresses: ["localhost:4161"]
          topic: my_topic
          channel: my_channel
          max_in_flight: 1000000
