fujin:
  enabled: true
  addr: :4848
  ping_interval: 5s
  ping_timeout: 10s
  ping_stream: false
  ping_max_retries: 5
  write_deadline: 10s
  force_terminate_timeout: 15s
  tls:
    enabled: true
    server_cert_pem_path: /assets/certs/fujin.io.pem
    server_key_pem_path: /assets/certs/fujin.io-key.pem
  quic:
    max_incoming_streams: 1000
    max_idle_timeout: 5s
    keepalive_period: 2s
  observability_enabled: false
grpc:
  enabled: true
  addr: :4849
  observability_enabled: false
connectors:
  mqtt_connector:
    protocol: mqtt
    settings:
      common:
        broker_url: tcp://localhost:1883
        keep_alive: 2s
        disconnect_timeout: 5s
      clients:
        pub:
          client_id: fujin_pub
          topic: my_topic
          qos: 0
          retain: false
          clean_start: true
          pool:
            size: 10000
            pre_alloc: true
            release_timeout: 5s
        sub:
          client_id: fujin_sub
          topic: my_topic
          qos: 0
          retain: false
          clean_start: true
