fujin:
  enabled: true
  tls:
    enabled: true
    server_cert_pem_path: /assets/certs/fujin.io.pem
    server_key_pem_path: /assets/certs/fujin.io-key.pem
grpc:
  enabled: true
connectors:
  resp_streams_connector:
    protocol: resp_streams
    settings:
      common:
        init_address: ["localhost:6379"]
      clients:
        pub:
          stream: stream
          batch_size: 1000
          linger: 10ms
          # marshaller: json
        sub:
          group:
            name: fujin
            consumer: fujin
          streams:
            stream:
              group_create_id: $
              start_id: ">"
          block: 3s
          # marshaller: json
