fujin:
  enabled: true
  addr: :4848
  ping_interval: 5s
  ping_timeout: 10s
  ping_stream: false
  ping_max_retries: 5
  write_deadline: 10s
  force_terminate_timeout: 15s
  tls:
    enabled: true
    server_cert_pem_path: /assets/certs/fujin.io.pem
    server_key_pem_path: /assets/certs/fujin.io-key.pem
  quic:
    max_incoming_streams: 1000
    max_idle_timeout: 5s
    keepalive_period: 2s
  observability_enabled: false
grpc:
  enabled: true
  addr: :4849
  observability_enabled: false
connectors:
  resp_streams_connector:
    protocol: resp_streams
    settings:
      common:
        init_address: ["localhost:6379"]
      clients:
        pub:
          stream: stream
          batch_size: 1000
          linger: 10ms
          # marshaller: json
        sub:
          group:
            name: fujin
            consumer: fujin
          streams:
            stream:
              group_create_id: $
              start_id: ">"
          block: 3s
          # marshaller: json
