fujin:
  enabled: true
  tls:
    enabled: true
    server_cert_pem_path: /assets/certs/fujin.io.pem
    server_key_pem_path: /assets/certs/fujin.io-key.pem
grpc:
  enabled: true
connectors:
  nsq_connector:
    protocol: nsq
    settings:
      common: {}
      clients:
        pub:
          address: "localhost:4150"
          topic: my_topic
          pool:
            size: 10000
            pre_alloc: true
            release_timeout: 5s
        sub:
          addresses: ["localhost:4150"]
          # lookupd_addresses: ["localhost:4161"]
          topic: my_topic
          channel: my_channel
          max_in_flight: 1000000
