fujin:
  enabled: true
  tls:
    enabled: true
    server_cert_pem_path: /assets/certs/fujin.io.pem
    server_key_pem_path: /assets/certs/fujin.io-key.pem
grpc:
  enabled: true
connectors:
  amqp091_connector:
    protocol: amqp091
    settings:
      common: {}
      clients:
        pub:
          conn:
            url: amqp://guest:guest@localhost
          exchange:
            name: events
            kind: fanout
          queue:
            name: my_queue
          queue_bind:
            binding_key: my_routing_key
          publish:
            content_type: text/plain
        sub:
          conn:
            url: amqp://guest:guest@localhost
          exchange:
            name: events
            kind: fanout
          queue:
            name: my_queue
          queue_bind:
            routing_key: my_routing_key
          consume:
            consumer: fujin
          nack:
            requeue: true
