fujin:
  enabled: true
  tls:
    enabled: true
    server_cert_pem_path: /assets/certs/fujin.io.pem
    server_key_pem_path: /assets/certs/fujin.io-key.pem
grpc:
  enabled: true
connectors:
  nats_core_connector:
    protocol: nats_core
    settings:
      common:
        url: nats://localhost:4222
      clients:
        pub:
          subject: my_subject
        sub:
          subject: my_subject
