fujin:
  enabled: true
  addr: :4848
  ping_interval: 5s
  ping_timeout: 10s
  ping_stream: false
  ping_max_retries: 5
  write_deadline: 10s
  force_terminate_timeout: 15s
  tls:
    enabled: true
    server_cert_pem_path: /assets/certs/fujin.io.pem
    server_key_pem_path: /assets/certs/fujin.io-key.pem
  quic:
    max_incoming_streams: 1000
    max_idle_timeout: 5s
    keepalive_period: 2s
  observability_enabled: false
grpc:
  enabled: true
  addr: :4849
  observability_enabled: false
connectors:
  amqp10_connector:
    protocol: amqp10
    settings:
      common: {}
      clients:
        pub:
          conn:
            addr: amqp://artemis:artemis@localhost:61616
          sender:
            target: exchange
        sub:
          conn:
            addr: amqp://artemis:artemis@localhost:61616
          receiver:
            source: exchange
