fujin:
  enabled: true
  tls:
    enabled: true
    server_cert_pem_path: ./examples/assets/certs/fujin.io.pem
    server_key_pem_path: ./examples/assets/certs/fujin.io-key.pem
grpc:
  enabled: true
connectors:
  kafka_connector:
    protocol: kafka
    settings:
      common:
        brokers: [kafka1:19092, kafka2:19093, kafka3:19094]
      clients:
        pub:
          allow_auto_topic_creation: true
          produce_topic: my_pub_topic
        sub:
          consume_topics: [my_pub_topic]
          group: fujin
          allow_auto_topic_creation: true