services:
  fujin:
    image: fujin:amqp10-${BUILD_TAG}
    build:
      context: ..
      args:
        GO_BUILD_TAGS: fujin,grpc,amqp10,observability
    container_name: fujin
    ports:
      - "4848:4848/udp"
      - "4949:4949"
    volumes:
      - ./assets:/assets
    command: /assets/config/config-amqp10.yaml
    restart: always