services:
  fujin:
    image: fujin:kafka-${BUILD_TAG}
    build:
      context: ..
      args:
        GO_BUILD_TAGS: fujin,grpc,kafka,observability
    container_name: fujin
    ports:
      - "4848:4848/udp"
      - "4949:4949"
    volumes:
      - ./assets:/assets
    command: /assets/config/config-kafka.yaml
    restart: always