services:
  fujin:
    image: fujin:mqtt-${BUILD_TAG}
    build:
      context: ..
      args:
        GO_BUILD_TAGS: fujin,grpc,mqtt,observability
    container_name: fujin
    ports:
      - "4848:4848/udp"
    volumes:
      - ./assets:/assets
    command: /assets/config/config-mqtt.yaml
    restart: always