services:
  fujin:
    image: fujin:resp_streams-${BUILD_TAG}
    build:
      context: ..
      args:
        GO_BUILD_TAGS: fujin,grpc,resp_streams,observability
    container_name: fujin
    ports:
      - "4848:4848/udp"
    volumes:
      - ./assets:/assets
    command: /assets/config/config-resp_streams.yaml
    restart: always