services:
  fujin:
    image: fujin:amqp091-${BUILD_TAG}
    build:
      context: ..
      args:
        GO_BUILD_TAGS: fujin,grpc,amqp091,observability
    container_name: fujin
    ports:
      - "4848:4848/udp"
    volumes:
      - ./assets:/assets
    command: /assets/config/config-amqp091.yaml
    restart: always