services:
  fujin:
    image: fujin:nats_core-${BUILD_TAG}
    build:
      context: ..
      args:
        GO_BUILD_TAGS: fujin,grpc,nats_core,observability
    container_name: fujin
    ports:
      - "4848:4848/udp"
    volumes:
      - ./assets:/assets
    command: /assets/config/config-nats_core.yaml
    restart: always