services:
  fujin:
    image: fujin:amqp10-${BUILD_TAG}
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        FUJIN_CONNECTORS: amqp10
        FUJIN_GO_TAGS: fujin,grpc
    container_name: fujin
    environment:
      FUJIN_CONFIGURATOR: file
      FUJIN_CONFIGURATOR_FILE_PATHS: /assets/config/config-amqp10.yaml
    ports:
      - "4848:4848/udp"
      - "4849:4849"
    volumes:
      - ./assets:/assets
    restart: always